config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  authenticated :user do
    root "dashboard#main", as: :authenticated_root
  end

  devise_scope :user do
    root "devise/sessions#new"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :practice

  validates :user_id, uniqueness: { scope: :practice_id, message: "already has an attendance record for this practice" }
end

app/models/fine.rb
class Fine < ApplicationRecord
  belongs_to :user

  validates :paid, inclusion: { in: [ true, false ] }

  enum :fine_type, {
    lost_game: 0,
    goal_conceded: 1,
    late_for_game: 2,
    missed_penalty: 3,
    debut: 4,
    clothes_not_turned_inside_out: 5,
    more_than_seven_votes_mvp: 6,
    yellow_card: 7,
    stupid_yellow_card: 8,
    red_card: 9,
    stupid_red_card: 10,
    tape_on_boot: 11,
    birthday_on_matchday: 12,
    new_cleats: 13,
    drinking_before_cheers: 14,
    absence_without_notice: 15,
    old_man_injury: 16,
    lost_goods: 17,
    phone_under_tactics: 18,
    stripping_before_mvp: 19,
    spilled_drink: 20,
    the_cream_fine: 21,
    urination_in_the_shower: 22,
    style_hair_before_game: 23,
    complaints_to_fine_manager: 24,
    holes_in_boxers: 25,
    the_smelly_fine: 26,
    the_daddy_fine: 27,
    new_house_car: 28,
    dirty_from_shower: 29,
    no_celebration: 30,
    forgot_cleats_matchday: 31
  }

  def pretty_fine_type
    I18n.t("enum.fine_type.#{fine_type}")
  end
end

app/models/practice.rb
class Practice < ApplicationRecord
  has_many :attendances, dependent: :destroy
  has_many :players, through: :attendances, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :role

  enum :role, { unregistered: 0, player: 1, coach: 2, administrator: 3 }

  has_one_attached :avatar

  validates :avatar, content_type: [ "image/png", "image/jpeg" ],
                    size: { less_than: 2.megabytes, message: "should be less than 2MB" }

  has_many :fines, dependent: :destroy
  has_many :attendances
  has_many :practices, through: :attendances

  def total_contribution
    fines.where(paid: true).sum(:amount)
  end

  def pending_balance
    balance - fines.where(paid: false).sum(:amount)
  end

  def display_unpaid_fines
    "#{fines.where(paid: false).count} ikke betalt" if fines.where(paid: false).count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_locale
  protect_from_forgery

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :name ])
    devise_parameter_sanitizer.permit(:account_update, keys: [ :avatar, :name ])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def main
    @players_by_fines = User.left_joins(:fines)
    .group(:id)
    .having("SUM(fines.amount) > 0")
    .order(Arel.sql("SUM(fines.amount) DESC"))
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  layout "application", only: [ :edit ]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="da">
  <head>
    <title><%= content_for(:title) || "SIF Holbæk Bødekasse" %></title>
    <meta name="description" content="Dashboard for managing soccer club teams, fines, and related information.">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <script>
      if (localStorage.getItem('darkMode') === 'false' || !('darkMode' in localStorage)) {
        document.querySelector('html').classList.remove('dark');
        document.querySelector('html').style.colorScheme = 'light';
      } else {
        document.querySelector('html').classList.add('dark');
        document.querySelector('html').style.colorScheme = 'dark';
      }
    </script>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= vite_client_tag %>
    <%= vite_stylesheet_tag 'application', rel: 'stylesheet', data: { "turbo-track": "reload" } %>
    <%= vite_javascript_tag 'application' %>
    <%= vite_javascript_tag 'dashboard_charts' %>
  </head>

<body
    class="font-inter antialiased bg-gray-100 dark:bg-gray-900 text-gray-600 dark:text-gray-400"
    :class="{ 'sidebar-expanded': sidebarExpanded }"
    x-data="{ sidebarOpen: false, sidebarExpanded: localStorage.getItem('sidebar-expanded') == 'true' }"
    x-init="$watch('sidebarExpanded', value => localStorage.setItem('sidebar-expanded', value))"
>
    <script>
      if (localStorage.getItem('sidebar-expanded') == 'true') {
        document.querySelector('body').classList.add('sidebar-expanded');
      } else {
        document.querySelector('body').classList.remove('sidebar-expanded');
      }
    </script>
    <%= render partial:'partials/alert', locals: { message: alert } if alert %>
      <%= render partial: 'partials/notice', locals: { message: notice } if notice %>
    <div class="flex h-[100dvh] overflow-hidden">
      <%= render partial: 'partials/sidebar' %>
      <div class="relative flex flex-col flex-1 overflow-y-auto overflow-x-hidden">
        <%= render partial: 'partials/header', locals: { user: current_user } %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "SIF Holbæk Bødekasse" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <script>
      if (localStorage.getItem('darkMode') === 'false' || !('darkMode' in localStorage)) {
        document.querySelector('html').classList.remove('dark');
        document.querySelector('html').style.colorScheme = 'light';
      } else {
        document.querySelector('html').classList.add('dark');
        document.querySelector('html').style.colorScheme = 'dark';
      }
    </script>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= vite_client_tag %>
    <%= vite_stylesheet_tag 'application', data: { "turbo-track": "reload" } %>
    <%= vite_javascript_tag 'application' %>
    <%= vite_javascript_tag 'dashboard_charts' %>
  </head>

  <body class="font-inter antialiased bg-gray-100 dark:bg-gray-900 text-gray-600 dark:text-gray-400">
    <script>
      if (localStorage.getItem('sidebar-expanded') == 'true') {
          document.querySelector('body').classList.add('sidebar-expanded');
      } else {
            document.querySelector('body').classList.remove('sidebar-expanded');
      }
    </script>
    <div class="flex h-[100dvh] overflow-hidden">
      <%= render partial:'partials/alert', locals: { message: alert } if alert %>
      <%= render partial: 'partials/notice', locals: { message: notice } if notice %>
      <div class="relative flex flex-col flex-1 overflow-y-auto overflow-x-hidden">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/partials/_alert.html.erb
<div x-show="open" x-data="{ open: true }" role="alert" class="alert fixed top-4 left-1/2 transform -translate-x-1/2 z-50 w-[800px]">
  <div class="inline-flex flex-col w-full px-6 py-4 rounded-lg text-sm bg-white dark:bg-gray-800 shadow-sm border border-gray-200 dark:border-gray-700/60 text-gray-600 dark:text-gray-400">
    <div class="flex w-full justify-between items-start">
      <div class="flex">
        <svg class="shrink-0 fill-current text-red-500 mt-[3px] mr-3" width="16" height="16" viewBox="0 0 16 16">
          <path
            d="M8 0C3.6 0 0 3.6 0 8s3.6 8 8 8 8-3.6 8-8-3.6-8-8-8zm3.5 10.1l-1.4 1.4L8 9.4l-2.1 2.1-1.4-1.4L6.6 8 4.5 5.9l1.4-1.4L8 6.6l2.1-2.1 1.4 1.4L9.4 8l2.1 2.1z" />
        </svg>
        <div>
          <div class="font-medium text-gray-800 dark:text-gray-100 mb-1">Der skete en fejl</div>
          <div>
            <%= message %>
          </div>
        </div>
      </div>
      <button class="opacity-60 hover:opacity-70 ml-3 mt-[3px]" @click="open = false">
        <div class="sr-only">Close</div>
        <svg class="fill-current" width="16" height="16" viewBox="0 0 16 16">
          <path
            d="M7.95 6.536l4.242-4.243a1 1 0 111.415 1.414L9.364 7.95l4.243 4.242a1 1 0 11-1.415 1.415L7.95 9.364l-4.243 4.243a1 1 0 01-1.414-1.415L6.536 7.95 2.293 3.707a1 1 0 011.414-1.414L7.95 6.536z" />
        </svg>
      </button>
    </div>
  </div>
</div>

app/views/partials/_notice.html.erb
<div x-show="open" x-data="{ open: true }" role="alert" class="notice fixed top-4 left-1/2 transform -translate-x-1/2 z-50 w-[800px]">
  <div class="inline-flex flex-col w-full max-w-lg px-4 py-2 rounded-lg text-sm bg-white dark:bg-gray-800 shadow-sm border border-gray-200 dark:border-gray-700/60 text-gray-600 dark:text-gray-400">
    <div class="flex w-full justify-between items-start">
      <div class="flex">
        <svg class="shrink-0 fill-current text-violet-500 mt-[3px] mr-3" width="16" height="16" viewBox="0 0 16 16">
          <path d="M8 0C3.6 0 0 3.6 0 8s3.6 8 8 8 8-3.6 8-8-3.6-8-8-8zm1 12H7V7h2v5zM8 6c-.6 0-1-.4-1-1s.4-1 1-1 1 .4 1 1-.4 1-1 1z" />
        </svg>
        <div>
          <div class="font-medium text-gray-800 dark:text-gray-100 mb-1">Notifikation</div>
          <div><%= message %></div>
        </div>
      </div>
      <button class="opacity-60 hover:opacity-70 ml-3 mt-[3px]" @click="open = false">
        <div class="sr-only">Close</div>
        <svg class="fill-current" width="16" height="16" viewBox="0 0 16 16">
          <path d="M7.95 6.536l4.242-4.243a1 1 0 111.415 1.414L9.364 7.95l4.243 4.242a1 1 0 11-1.415 1.415L7.95 9.364l-4.243 4.243a1 1 0 01-1.414-1.415L6.536 7.95 2.293 3.707a1 1 0 011.414-1.414L7.95 6.536z" />
        </svg>
      </button>
    </div>
    <%# <div class="text-right mt-1">
      <a class="font-medium text-violet-500 hover:text-violet-600 dark:hover:text-violet-400" href="#0">Action -&gt;</a>
    </div> %>
  </div>
</div>

app/views/partials/_sidebar.html.erb
<!-- Sidebar -->
<div class="min-w-fit">
  <!-- Sidebar backdrop (mobile only) -->
  <div class="fixed inset-0 bg-gray-900 bg-opacity-30 z-40 lg:hidden lg:z-auto transition-opacity duration-200"
    :class="sidebarOpen ? 'opacity-100' : 'opacity-0 pointer-events-none'" aria-hidden="true" x-cloak></div>

  <!-- Sidebar -->
  <div id="sidebar"
    class="flex flex-col absolute z-40 left-0 top-0 lg:static lg:left-auto lg:top-auto lg:translate-x-0 h-[100dvh] overflow-y-scroll lg:overflow-y-auto no-scrollbar w-64 lg:w-20 lg:sidebar-expanded:!w-64 2xl:!w-64 shrink-0 bg-white dark:bg-gray-800 shadow-sm rounded-r-2xl p-4 transition-all duration-200 ease-in-out"
    :class="sidebarOpen ? 'translate-x-0' : '-translate-x-64'" @click.outside="sidebarOpen = false"
    @keydown.escape.window="sidebarOpen = false" x-cloak="lg">

    <!-- Sidebar header -->
    <div class="flex justify-between mb-10 pr-3 sm:px-2">
      <!-- Close button -->
      <button class="lg:hidden text-gray-500 hover:text-gray-400" @click.stop="sidebarOpen = !sidebarOpen"
        aria-controls="sidebar" :aria-expanded="sidebarOpen">
        <span class="sr-only">Close sidebar</span>
        <svg class="w-6 h-6 fill-current" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
          <path d="M10.7 18.7l1.4-1.4L7.8 13H20v-2H7.8l4.3-4.3-1.4-1.4L4 12z" />
        </svg>
      </button>
      <!-- Logo -->
      <%= link_to authenticated_root_path, class: 'block' do %>
        <%= image_tag 'small_logo.png', class: 'fill-violet-500', alt: 'SIF Holbæk Logo' %>
      <% end %>
      <span class="hidden md:block text-sm pt-1" x-show="sidebarExpanded">SIF HOLBÆK</span>
    </div>

    <!-- Links -->
    <div class="space-y-8">
      <!-- Pages group -->
      <div>
        <h3 class="text-xs uppercase text-gray-400 dark:text-gray-500 font-semibold pl-3">
          <span class="hidden lg:block lg:sidebar-expanded:hidden 2xl:hidden text-center w-6"
            aria-hidden="true">•••</span>
          <span class="lg:hidden lg:sidebar-expanded:block 2xl:block">Menu</span>
        </h3>
        <ul class="mt-3">
          <!-- Dashboard -->
          <li class="pl-4 pr-3 py-2 rounded-lg mb-0.5 last:mb-0">
            <%= link_to authenticated_root_path, class: 'block text-gray-800 dark:text-gray-100 hover:text-gray-900 dark:hover:text-white truncate transition' do %>
              <div class="flex items-center">
                <svg class="shrink-0 fill-current <%= current_page?(authenticated_root_path) ? 'text-violet-500' : 'text-gray-500 dark:text-gray-400' %>" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
                  <path d="M5.936.278A7.983 7.983 0 0 1 8 0a8 8 0 1 1-8 8c0-.722.104-1.413.278-2.064a1 1 0 1 1 1.932.516A5.99 5.99 0 0 0 2 8a6 6 0 1 0 6-6c-.53 0-1.045.076-1.548.21A1 1 0 1 1 5.936.278Z" />
                  <path d="M6.068 7.482A2.003 2.003 0 0 0 8 10a2 2 0 1 0-.518-3.932L3.707 2.293a1 1 0 0 0-1.414 1.414l3.775 3.775Z" />
                </svg>
                <span class="text-sm font-medium ml-4 lg:opacity-0 lg:sidebar-expanded:opacity-100 2xl:opacity-100 duration-200">Dashboard</span>
              </div>
            <% end %>
          </li>
          <!-- Attendance -->
          <li class="pl-4 pr-3 py-2 rounded-lg mb-0.5 last:mb-0">
            <%= link_to authenticated_root_path, class: 'block text-gray-800 dark:text-gray-100 hover:text-gray-900 dark:hover:text-white truncate transition' do %>
              <div class="flex items-center">
                <svg class="shrink-0 fill-current text-gray-400 dark:text-gray-500" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
                  <path d="M6.753 2.659a1 1 0 0 0-1.506-1.317L2.451 4.537l-.744-.744A1 1 0 1 0 .293 5.207l1.5 1.5a1 1 0 0 0 1.46-.048l3.5-4ZM6.753 10.659a1 1 0 1 0-1.506-1.317l-2.796 3.195-.744-.744a1 1 0 0 0-1.414 1.414l1.5 1.5a1 1 0 0 0 1.46-.049l3.5-4ZM8 4.5a1 1 0 0 1 1-1h6a1 1 0 1 1 0 2H9a1 1 0 0 1-1-1ZM9 11.5a1 1 0 1 0 0 2h6a1 1 0 1 0 0-2H9Z" />
                </svg>
                <span class="text-sm font-medium ml-4 lg:opacity-0 lg:sidebar-expanded:opacity-100 2xl:opacity-100 duration-200">Attendance</span>
              </div>
            <% end %>
          </li>
          <!-- Calendar -->
          <li class="pl-4 pr-3 py-2 rounded-lg mb-0.5 last:mb-0">
            <a class="block text-gray-800 dark:text-gray-100 hover:text-gray-900 dark:hover:text-white truncate transition"
              href="calendar.html">
              <div class="flex items-center">
                <svg class="shrink-0 fill-current text-gray-400 dark:text-gray-500" xmlns="http://www.w3.org/2000/svg"
                  width="16" height="16" viewBox="0 0 16 16">
                  <path d="M5 4a1 1 0 0 0 0 2h6a1 1 0 1 0 0-2H5Z" />
                  <path
                    d="M4 0a4 4 0 0 0-4 4v8a4 4 0 0 0 4 4h8a4 4 0 0 0 4-4V4a4 4 0 0 0-4-4H4ZM2 4a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V4Z" />
                </svg>
                <span
                  class="text-sm font-medium ml-4 lg:opacity-0 lg:sidebar-expanded:opacity-100 2xl:opacity-100 duration-200">Calendar</span>
              </div>
            </a>
          </li>
        </ul>
      </div>
      <div>
        <h3 class="text-xs uppercase text-gray-400 dark:text-gray-500 font-semibold pl-3">
          <span class="hidden lg:block lg:sidebar-expanded:hidden 2xl:hidden text-center w-6"
            aria-hidden="true">•••</span>
          <span class="lg:hidden lg:sidebar-expanded:block 2xl:block">Administration</span>
        </h3>
      </div>
    </div>

    <!-- Expand / collapse button -->
    <div class="pt-3 hidden lg:inline-flex 2xl:hidden justify-end mt-auto">
      <div class="w-12 pl-4 pr-3 py-2">
        <button class="text-gray-400 hover:text-gray-500 dark:text-gray-500 dark:hover:text-gray-400 transition-colors"
          @click="sidebarExpanded = !sidebarExpanded">
          <span class="sr-only">Expand / collapse sidebar</span>
          <svg class="shrink-0 fill-current text-gray-400 dark:text-gray-500 sidebar-expanded:rotate-180"
            xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
            <path
              d="M15 16a1 1 0 0 1-1-1V1a1 1 0 1 1 2 0v14a1 1 0 0 1-1 1ZM8.586 7H1a1 1 0 1 0 0 2h7.586l-2.793 2.793a1 1 0 1 0 1.414 1.414l4.5-4.5A.997.997 0 0 0 12 8.01M11.924 7.617a.997.997 0 0 0-.217-.324l-4.5-4.5a1 1 0 0 0-1.414 1.414L8.586 7M12 7.99a.996.996 0 0 0-.076-.373Z" />
          </svg>
        </button>
      </div>
    </div>
  </div>
</div>